### ISSUE TITLE
login errors are not handled, making them impossible to catch

### ISSUE THREAD

**Issue by MendyLanda** [Hacksore/drone-mobile#12]
Since the class calls the login method internally, if it errors you cannot catch it. 
Making a PR to emit an error event in this case.

**Comment by MendyLanda** [comment]
@Hacksore that was quick! I appreciate it, thanks!

**Comment by Hacksore** [comment]
no problem getting the latest version published now, also the `dont @ me` is just a meme 😆.

**Comment by MendyLanda** [comment]
Deployed the fix, thanks again @Hacksore 
<img width="625" alt="image" src="https://github.com/Hacksore/drone-mobile/assets/54242706/5dbb58cd-106c-4443-86ec-220f8d1a8359">
