### ISSUE TITLE
Hello. 

### ISSUE THREAD

**Issue by aaronkt** [Hacksore/drone-mobile#6]
I am sorry but I seem to be a little to vanilla to under stand half of this. Is there a way to select each vehicle? I have two on my account. Also just examples of commands would be helpful for a start.

I basically wanna try to make a script that I can use a Linux container to run 15 minutes before I clock out from work. Before this cold winter sets in.

**Comment by Hacksore** [comment]
@aaronkt 

Documentation on this repo is pretty scarce since it's not all that popular 😅.

From the example, you can get access to all the vehicles by invoking `vehicles()`.

Like so:

```js
const DroneMobile = require("drone-mobile");
const client = new DroneMobile({
  username: "some@dude.com",
  password: "hunter1",
});

client.on("ready", async () => {
  // get a list of vehicles on the account
  const vehicleList = await client.vehicles();

  // vhicle id 1
  const vehicle1 = vehicleList[0];

  // vehicle id 2
  const vehicle2 = vehicleList[1];

  // print the vehicle ids
  console.log(vehicle1.device_key, vehicle2.device_key);

  // start vehicle 1
  console.log("Attempting to lock car", vehicle1.device_key);
  try {
    const response = await client.start(vehicle1.device_key);
    console.log(response);
  } catch (err) {
    console.log("Err:", err);
  }
});

**Comment by aaronkt** [comment]
It's sad that it isn't more popular. I will have to play around with it tomorrow morning thanks. I am just not used to nodejs. Tried to use the python version the other person made. That kept yelling at me. Then was going to try home assistant but by the time I got it spun up on proxmox I had to leave for work.

Thank you for your time. Hopefully I can stumble my way through it.

**Comment by aaronkt** [comment]
So to try and get this to work I am using node js on windows now

I have crates a drone.js file containing the test code, but with my log in details. So once I have that created and try to run it using node drone.js. I get this kind of an error

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: 'ERR_UNHANDLED_REJECTION'

I have the js file in the node_modules folder that node js created when I installed it.

I had the same type of error on Linux, which is why I tried windows now. Unfortunately to no help. I did try to just change the vehicle number also to see if maybe it wasn't finding anything? I am not really getting any usable information back from the commands.

Thanks for your time, and the project. Sorry I am having issues

**Comment by Hacksore** [comment]
@aaronkt Not able to see the same issue. Could you share what node version you are running?

![image](https://user-images.githubusercontent.com/996134/141351999-c6c87443-818e-46e7-a4d9-a3af57dbdf5e.png)

**Comment by aaronkt** [comment]
@Hacksore

Looks like I am running v16. 13.0

**Comment by Hacksore** [comment]
@aaronkt I'm on `v16.10.0` and don't run into the same issue.

One thing you can do is use `LOG_LEVEL=debug node drone.js` and share any errors after you have removed the sensitive data.

**Comment by aaronkt** [comment]
Thanks. I will have to look into that tomorrow or tonight unfortunately. Thank again. I did see you have " instead of ' like what I pulled from your example. No luck just changing all those.

**Comment by aaronkt** [comment]
Actually just pulled the one you commented here and input my information. Still same issue. I'll have to figure out how to get a debug for you. I've been running it with debugging and getting the sane thing.

**Comment by Hacksore** [comment]
@aaronkt you should expect to see something like this, which could help us find any issues with your account logging in.

![image](https://user-images.githubusercontent.com/996134/141355214-951e5a16-ead1-48c6-bf41-dde843e019f9.png)

**Comment by aaronkt** [comment]
```
/* eslist-disable  */
const DroneMobile = require("drone-mobile");
const client = new DroneMobile({
  username: "Removed",
  password: "Removed",
});

client.on("ready", async () => {
  // get a list of vehicles on the account
  const vehicleList = await client.vehicles();

  // vhicle id 1
  const vehicle1 = vehicleList[0];

  // vehicle id 2
  const vehicle2 = vehicleList[1];

  // print the vehicle ids
  console.log(vehicle2.device_key);

  // start vehicle 1
  console.log("Attempt to start car", vehicle2.device_key);
  try {
    const response = await client.start(vehicle1.device_key);
    console.log(response);
  } catch (err) {
    console.log("Err:", err);
  }
});
```
@Hacksore 

So this is where I am at. I am getting a response but then the vehicle is showing to be in a paused state. I did make sure this is the correct vehicle by using the ID.

**Comment by Hacksore** [comment]
@aaronkt Am I good to close this out then?

**Comment by aaronkt** [comment]
yes thank you for your time
