### ISSUE TITLE
Start Stop Toggle?

### ISSUE THREAD

**Issue by Swap-File** [Hacksore/drone-mobile#7]
I've noticed that if I issue a stop to a stopped car it will turn on, and if I issue a start to a started car it will turn off.

Has anyone else experienced this?  Or is there something weird on my end?

Is this a limitation of the drone backend?  I can wrap my start and stop commands with a check for the current car state if I need to, but it might be useful to document for others.

**Comment by aaronkt** [comment]
My car does the same thing when it is running. I know form the DM app the "running" status doesn't seem to be accurate for me half the time. My remote is better at telling me if it running.

**Comment by Swap-File** [comment]
Running state in the official drone mobile app seems to be accurate if I have "Auto-Refresh" turned on.  Otherwise sometimes it can take 5-30 seconds to be pushed notification of a start or stop initiated from my Compustar FOB.

I did notice something rather important:

If I start my car with my key, and then use the drone API directly to issue a start or a stop command, the car will shut off!  The Drone mobile app doesn't let me do this, and neither does attempting a remote start with my fob (they just make my headlights blink).

A variable called "remote_start_status" is set to "true" if I start my car via the app, API, or compustar FOB.  The app must be checking this before issuing a stop.

I'm not sure if any other variables should be checked, but minimally I'd recommend issuing a location command to refresh all the car's data, then issue a status command to get the entire current state, and then checking that "remote_start_status" == "true" and "engine_on" == "true" before issuing a stop command.  And before issuing a start command I'd minimally check that "engine_on" == "false".

**Comment by aaronkt** [comment]
Very interesting, good to know. May need to do some testing with mine. Assuming you have a two way system? Unfortunately I don't share a need to really have the check as mine is just set to start my car 15 minutes before I clock out of work. I do want to try and dockertize the program so I can move it off my proxmox server to my raspberry pi docker host.

**Comment by Swap-File** [comment]
If your drone install works the same as mine, the risk would be that if you leave work 15 minutes early and your remote start script triggers while you are driving home, it could shut your car off while you were in motion (unless you do some extra checks in your code).

**Comment by aaronkt** [comment]
Is your vehicle push to start??? Thankfully I have a key so ideally it should stop any other interaction if I am in motion.

**Comment by Swap-File** [comment]
Yeah, push to start. 

It seems very odd that only using the API directly will cause this behavior.  Both the Compustar T12 FOB and Drone Mobile app can't shut down my car after it's been locally started, but somehow using the API directly and requesting either a start or stop can.

**Comment by aaronkt** [comment]
And you haven't found a good way to check first?? It's a shame more people
aren't using this setup. Wouldn't easier to figure out this stuff.

**Comment by Swap-File** [comment]
The check isn't hard to do in software, but something is poorly designed on Drone Mobile's part if a software check like this is required. 

Something like this should work, but it's not fully tested:

```
  const location_resp = await client.location(vehicle.device_key);
  const status_resp = await client.status(vehicle.device_key);
   if( status_resp["remote_start_status"] == false &&  location_resp["parsed"]["controller"]["engine_on"] == true){
	   reply = "Car In Use!";
   } else {
  // Do stuff here.
}
```

**Comment by Swap-File** [comment]
This is the code I am currently using with my home automation software, I give it my request as an argument, and it returns a short bit of text that my smart watch can display, enabling Drone Mobile control from my watch.

L = Locked
U = Unlocked
T = Trunk (or other door) Open
S = Started
s = Stopped
H = Started and Heated Seats triggered
C = Started and Cooled Seats triggered
h = Heated seats triggered
c = Cooling seats triggered


```
var request = process.argv[2];

if (request == "FONT"){
	console.log("{\"result\":\"70°F 12.0V C\"}" );
	process.exit(1);
}

const DroneMobile = require('drone-mobile');
const client = new DroneMobile({
username: '',
password: ''
});


client.on('ready', async () => {
	// get a list of vehicles on the account
	const vehicleList = await client.vehicles();

	// pick the first one
	const vehicle = vehicleList[0];

	try {
		const location_resp = await client.location(vehicle.device_key);
		const status_resp = await client.status(vehicle.device_key);

		reply_temp = Math.round((location_resp["parsed"]["controller"]["current_temperature"] * 9/5) + 32) + "°F" 
		reply_voltage = location_resp["parsed"]["controller"]["main_battery_voltage"]+"V";
		
		state_now = "";
		state_future= "";

		if( status_resp["remote_start_status"] == false &&  location_resp["parsed"]["controller"]["engine_on"] == true){
			console.log("{\"result\":\"Car In Use!\"}" );	
		} else {

			// determine current state
			if (location_resp["parsed"]["controller"]["armed"] == true){
				state_now = "L"
			}else{
				state_now = "U"
			}
			
			if (location_resp["parsed"]["controller"]["door_open"] == true || location_resp["parsed"]["controller"]["trunk_open"] == true  || location_resp["parsed"]["controller"]["hood_open"] == true){
				state_now = "T"
			}
			
			if (status_resp["last_known_state"]["controller"]["engine_on"] == true ){
				state_now = "S"
			}
			
			// execute future state
			if (request == "LOCK"){
				if (location_resp["parsed"]["controller"]["armed"] == false){
					await client.lock(vehicle.device_key);
					state_future = "L";
				}		
			}
			if (request == "UNLOCK"){
				if (location_resp["parsed"]["controller"]["armed"] == true){
					await client.unlock(vehicle.device_key);
					state_future = "U";
				}
			}
			if (request == "TRUNK"){
				await client.trunk(vehicle.device_key);
				state_future = "T";
			}
			if (request == "START"){
				if (status_resp["last_known_state"]["controller"]["engine_on"] == false){
					await client.start(vehicle.device_key);
					state_future = "S";					
				}
			}
			if (request == "STOP"){
				if (status_resp["last_known_state"]["controller"]["engine_on"] == true){
					await client.start(vehicle.device_key);
					state_future = "s";
				}
			}
			if (request == "HEAT"){
				if (status_resp["last_known_state"]["controller"]["engine_on"] == true){
					await client.aux1(vehicle.device_key);
					state_future = "h";
				}else{
					await client.start(vehicle.device_key);
					await new Promise(r => setTimeout(r, 15000));
					await client.aux1(vehicle.device_key);
					state_future = "H";
				}
			}
			if (request == "COOL"){
				if (status_resp["last_known_state"]["controller"]["engine_on"] == true){
					await client.aux2(vehicle.device_key);
					state_future = "C";
				}else{
					await client.start(vehicle.device_key);
					await new Promise(r => setTimeout(r, 15000));
					await client.aux2(vehicle.device_key);
					state_future = "c";
				}
			}
			console.log("{\"result\":\"" + reply_temp + " " + reply_voltage + " " + state_now + state_future + "\"}" );	
		}
	} catch (err) {
		console.log("{\"result\":\"Error\"}" );	
	}
});
```
