### ISSUE TITLE
drone-mobile used for Node-RED flow

### ISSUE THREAD

**Issue by deek042** [Hacksore/drone-mobile#8]
@Hacksore 
I used your work in creating a Node-RED flow.
I have the Node-RED server and drone-mobile set up on my Raspberry Pi.

Just wanted to stop by and say I appreciate what you have created.
Thanks!

Here's the flow:
https://flows.nodered.org/flow/9c7a50c75ace34386963ffeeff871142

![2022-02-18 (8)](https://user-images.githubusercontent.com/97567657/154780214-17583c9e-9722-4989-b909-e2f96f32def1.png)

**Comment by Hacksore** [comment]
@deek042 cool stuff!

I think your flow is a bit hardcoded in some places for how it executes the scripts from my observations so not plug and play for everyone.

Maybe someone can look into building a proper node-red addon as has been done with one of my other libs.

https://github.com/SondreNjaastad/node-red-contrib-bluelinky

Anyways gonna close the issue but the continued discussion is always welcomed.
