### ISSUE TITLE
Unlock Car

### ISSUE THREAD

**Issue by isfatul** [Hacksore/drone-mobile#9]
I'm trying to unlock the car and it shows this error. 

(node:8372) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token E in JSON at position 0
    at JSON.parse (<anonymous>)
    at I:\Projects\react-pr\apicarapp\apicarapp-master\node_modules\drone-mobile\dist\index.js:17:966
    at Generator.next (<anonymous>)
    at r (I:\Projects\react-pr\apicarapp\apicarapp-master\node_modules\drone-mobile\dist\index.js:17:85)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by Hacksore** [comment]
@isfatul-codersbd Can you share the code you used without any sensitive infomration?

**Comment by isfatul-codersbd** [comment]
var client = new DroneMobile({
  username: "",
  password: "",
});

  client.on("ready", () => {
   try {
  const response =  client.unlock(req.body.sn);
   res.send("Unlocked");
    } catch (err) {
      res.send('Err:', err);
    }
});

**Comment by Hacksore** [comment]
@isfatul-codersbd looks like you might be trying to integrate with express? Here is an example of how to get the ID from the first vehicle on the account and requesting it to unlock.

If you're going to add in express or another web server you might want to have your code first set up the `DroneMoble` instance first before accepting requests.

```js
const DroneMobile = require("drone-mobile");

const client = new DroneMobile({
  username: "username",
  password: "password",
});

client.on("ready", async () => {
  try {
    const vehicles = await client.vehicles();
    const id = vehicles[0].device_key;
    console.log("Unlocking vehicle", id);
    await client.unlock(id);
  } catch (err) {
    console.log(err);
  }
});
```

Hope this helps.

**Comment by isfatul-codersbd** [comment]
![image](https://user-images.githubusercontent.com/39835738/155339530-f765f40b-959a-4c62-9b5e-7284d1a0379b.png)

Still gives this error after trying your code.
